[project]
name = "de-zoomcamp"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.43.71",
    "click>=8.4.2",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.2",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "notebook>=7.6.1",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
